name: mmdebstrap

on:
  push:
    branches: [ master ]

jobs:
  mmdebstrap:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
      options: --privileged

    strategy:
      matrix:
        arch: ["amd64"]
        version: ["buster"]
        variant: ["standard"]
        network: ["ifupdown"]
        # arch: ["armhf", "arm64", "amd64"]
        # version: ["stretch", "buster", "bullseye"]
        # variant: ["essential", "required", "important", "standard"]
        # network: ["ifupdown", "systemd-networkd", "network-manager"]

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y mmdebstrap

      - name: Create artifact
        run: |
          SYSTEM_PKGS=systemd-sysv,udev,linux-image-amd64
          MAIN_PKGS=debian-archive-keyring,initramfs-tools,kmod,e2fsprogs,btrfs-progs,locales,tzdata,apt-utils,whiptail,debconf-i18n,keyboard-configuration,console-setup
          NETWORK_PKGS=ifupdown,isc-dhcp-client
          mmdebstrap \
            --architectures=${{ matrix.arch }} \
            --variant=${{ matrix.variant }} \
            --components="main" \
            --include=$SYSTEM_PKGS,$MAIN_PKGS,$NETWORK_PKGS \
            ${{ matrix.version }} debian-${{ matrix.version }}-${{ matrix.variant }}-${{ matrix.arch }}.tar
